ISP_AE_V3 := 1
EXTRA_CFLAGS += -DISP_AE_V3

ISP_AWB_V3 := 1
EXTRA_CFLAGS += -DISP_AWB_V3

ISP_AF_V3 := 1
EXTRA_CFLAGS += -DISP_AF_V3

# ISP_GC_V1 := 1
# EXTRA_CFLAGS += -DISP_GC_V1

# ISP_2DNR_V3 := 1
# EXTRA_CFLAGS += -DISP_2DNR_V3

# ISP_EE_V1 := 1
# EXTRA_CFLAGS += -DISP_EE_V1

ISP_CPROC := 1
EXTRA_CFLAGS += -DISP_CPROC

# ISP_WDR_V3:= 1
# EXTRA_CFLAGS += -DISP_WDR_V3

ISP_BLS := 1
EXTRA_CFLAGS += -DISP_BLS

ISP_CCM := 1
EXTRA_CFLAGS += -DISP_CCM

ISP_DPCC := 1
EXTRA_CFLAGS += -DISP_DPCC

# ISP_LSC_V1 := 1
# EXTRA_CFLAGS += -DISP_LSC_V1

ISP_WB := 1
EXTRA_CFLAGS += -DISP_WB

# ISP_3DNR_V1_2 := 1
# EXTRA_CFLAGS += -DISP_3DNR_V1_2

ISP_AFM_V1 := 1
EXTRA_CFLAGS += -DISP_AFM_V1

# ISP_DMSC_V1 := 1
# EXTRA_CFLAGS += -DISP_DMSC_V1

ISP_EXP_V2 := 1
EXTRA_CFLAGS += -DISP_EXP_V2

# ISP_HDR_V1_3 := 1
# EXTRA_CFLAGS += -DISP_HDR_V1_3

# ISP_DG := 1
# EXTRA_CFLAGS += -DISP_DG

ISP_CPD := 1
EXTRA_CFLAGS += -DISP_CPD

# ISP_DPF_V1 := 1
# EXTRA_CFLAGS += -DISP_DPF_V1

# ISP_CNR_V1 := 1
# EXTRA_CFLAGS += -DISP_CNR_V1

# ISP_GWDR_V1 := 1
# EXTRA_CFLAGS += -DISP_GWDR_V1
