/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (C) 2019 Synaptics Incorporated */
#ifndef __AVIO_DHUB_CFG_PRV_H__
#define __AVIO_DHUB_CFG_PRV_H__
#define AG_NUM_OF_CHANNELS		(avioDhubChMap_aio64b_DRT_W + 1)
/*Total size = 0x5000 = 20480*/
#define AIO_DHUB_I2S1_R_SIZE		(2048)
#define AIO_DHUB_I2S1_W_SIZE		(1024)
#define AIO_DHUB_I2S2_R_SIZE		(2048)
#define AIO_DHUB_I2S2_W_SIZE		(1024)
#define AIO_DHUB_I2S3_R_SIZE		(2048)
#define AIO_DHUB_I2S3_W_SIZE		(1024)
#define AIO_DHUB_I2S4_R_SIZE		(2048)
#define AIO_DHUB_I2S4_W_SIZE		(1024)
#define AIO_DHUB_BCM_R_SIZE			(512)
#define AIO_DHUB_I2S5_R_SIZE		(2048)
#define AIO_DHUB_I2S5_W_SIZE		(1024)
#define AIO_DHUB_PDM_W_SIZE			(1024)
#define AIO_DHUB_PDM_R_SIZE			(1024)
#define AIO_DHUB_DCLASS_R_SIZE		(512)
#define AIO_DHUB_DRT_R_SIZE			(1024)
#define AIO_DHUB_DRT_W_SIZE			(1024)
#define AIO_DHUB_I2S1_R_BASE		(AG_DHUB_BANK0_START_ADDR)
#define AIO_DHUB_I2S1_W_BASE		(AIO_DHUB_I2S1_R_BASE+AIO_DHUB_I2S1_R_SIZE)
#define AIO_DHUB_I2S2_R_BASE		(AIO_DHUB_I2S1_W_BASE+AIO_DHUB_I2S1_W_SIZE)
#define AIO_DHUB_I2S2_W_BASE		(AIO_DHUB_I2S2_R_BASE+AIO_DHUB_I2S2_R_SIZE)
#define AIO_DHUB_I2S3_R_BASE		(AIO_DHUB_I2S2_W_BASE+AIO_DHUB_I2S2_W_SIZE)
#define AIO_DHUB_I2S3_W_BASE		(AIO_DHUB_I2S3_R_BASE+AIO_DHUB_I2S3_R_SIZE)
#define AIO_DHUB_I2S4_R_BASE		(AIO_DHUB_I2S3_W_BASE+AIO_DHUB_I2S3_W_SIZE)
#define AIO_DHUB_I2S4_W_BASE		(AIO_DHUB_I2S4_R_BASE+AIO_DHUB_I2S4_R_SIZE)
#define AIO_DHUB_BCM_R_BASE			(AIO_DHUB_I2S4_W_BASE+AIO_DHUB_I2S4_W_SIZE)
#define AIO_DHUB_I2S5_R_BASE		(AIO_DHUB_BCM_R_BASE+AIO_DHUB_BCM_R_SIZE)
#define AIO_DHUB_I2S5_W_BASE		(AIO_DHUB_I2S5_R_BASE+AIO_DHUB_I2S5_R_SIZE)
#define AIO_DHUB_PDM_W_BASE			(AIO_DHUB_I2S5_W_BASE+AIO_DHUB_I2S5_W_SIZE)
#define AIO_DHUB_PDM_R_BASE			(AIO_DHUB_PDM_W_BASE+AIO_DHUB_PDM_W_SIZE)
#define AIO_DHUB_DCLASS_R_BASE		(AIO_DHUB_PDM_R_BASE+AIO_DHUB_PDM_R_SIZE)
#define AIO_DHUB_DRT_R_BASE			(AIO_DHUB_DCLASS_R_BASE+AIO_DHUB_DCLASS_R_SIZE)
#define AIO_DHUB_DRT_W_BASE			(AIO_DHUB_DRT_R_BASE+AIO_DHUB_DRT_R_SIZE)
#define AG_DHUB_BANK0_START_ADDR	avioDhubTcmMap_aio64bDhub_BANK0_START_ADDR
#define AVIO_DHUB_INITCHANNELAXQOS(pdhubHandle, dhub_config, chanId, i, cfgQ)
#define AVIO_DHUB_MTR_CFG_QOS_EN	0
#define AVIO_DHUB_MTR_CFG_QOS		0
#define AVIO_DHUB_DESC_OVRDQOS		1
#define AVIO_DHUB_DESC_QOSSEL		1
#define IS_SINGLE_DISPLAY()			0
typedef struct DHUB_channel_config {
	SIGN32 chanId;
	UNSG32 chanCmdBase;
	UNSG32 chanDataBase;
	SIGN32 chanCmdSize;
	SIGN32 chanDataSize;
	SIGN32 chanMtuSize;
	SIGN32 chanQos;
	SIGN32 chanSelfLoop;
	SIGN32 chanEnable;
	UNSG32 chanAxQosLO;
	UNSG32 chanAxQosHI;
} DHUB_channel_config;
#endif /*__AVIO_DHUB_CFG_PRV_H__*/
